// CODEGEN-BEGIN
// AW-EC-BEGIN
// @ec vat-llm-agent-usage-guide
// @capability agent-native-gpu-native-dev-containers
// @claim agent-legible-state-and-diff-surface
// @contract agent-legible-state-and-diff-surface
// @category behavior
// @required_for_production true
// @command cargo test -p vat --test vat_toml_runner -- --nocapture
// AW-EC-END

// Contract: `vat llm --topic guide` exits successfully.
// Contract: The guide mentions vat.toml runner mode and direct command mode.
// Contract: The guide mentions state, diff, and logs evidence commands.
// Contract: The guide describes exact no-format and VAT-native Compose `ps --format json` / `--format=json` forms: JSON mode is one `vat.docker-compose.ps.v1` / `vat_json` document with no human table and the same claim-held profile/topology proof, not Docker Compose JSON/template/table compatibility; every other Compose ps format and invalid provenance fail closed. The full serial vat_docker_shim aggregate is intentionally not recorded because an independent serial run exposed a nondeterministic pre-existing Compose JSON logs timing race; no aggregate result is claimed for this sandbox.
// Contract: The guide describes strict `docker compose --dry-run -f FILE -p PROJECT up -d [--build]`: it parses only existing strict profiles and emits one vat.docker-compose.preflight.v1 document with validated=true, runtime_started=false, registry_written=false, image_built=false, launch_revalidates=true, launch_argv, and executable next using the parser's canonical source path; it invokes no Apple Container command, does not build/import/start/write registry, rejects wait and all other global/Compose flags, and real launch revalidates that same file after a cwd change.
// Contract: The guide describes text `logs SERVICE` preserving observed log bytes then starting its additive VAT handoff JSON on a new line after them, and `logs --format json [--tail LINES] SERVICE` capture-only VAT JSON: separate stdout/stderr, default 200/range 1..=1000 tail, truncated/utf8_lossy indicators, capture_only=true/runtime_invoked=false/compose_record_mutated=false, no topology/endpoints, and JSON-ps next. It holds existing claim/provenance without an Apple Container call or project.json mutation; VAT first caps each read and line tail, then after lossy UTF-8 plus JSON escaping retains a valid UTF-8 suffix whose serialized JSON string value remains within the same 64 KiB per-stream cap and marks it truncated. It rejects follow/timestamps/other flags and does not claim Docker Compose merged/follow/timestamp/template behavior. The full serial vat_docker_shim aggregate is intentionally not recorded because an independent serial run exposed a nondeterministic pre-existing Compose JSON logs timing race; the focused serialized-cap unit passed 1/1 for 0xff-heavy and NUL/control-heavy streams after actual JSON serialization. The recorded real dual-service E2E includes JSON logs for the bounded host-facing profile.
// Contract: The guide describes Compose text exec preserving observed child bytes then starting its additive VAT handoff JSON on a new line after them, and JSON only as `docker compose -p PROJECT exec -T --format json SERVICE -- COMMAND` or `--format=json`: one same-read claim-held snapshot requires known shim provenance plus exact unique ready VAT-owned MicroVM evidence through child spawn, VAT parses and validates the Docker-facing -- but does not forward it, invoking `container exec CONTAINER COMMAND [ARG...]`, then releases the claim, drains child stdout/stderr concurrently, and emits one VAT-native `vat.docker-compose.exec.v1` document with profile, child_exit_code, separate streams, per-stream truncated/utf8_lossy, runtime_invoked=true, compose_record_mutated=false, no raw child output, and no topology/endpoints. Each serialized stream string is capped at 64 KiB. Text ordering covers observed managed-child bytes only, not escaped descendants. Misordered format, missing delimiter, TTY, and all other exec flags fail closed; it is not Docker Compose exec-output compatibility. The full serial shim aggregate is intentionally not recorded because an independent serial run exposed a nondeterministic pre-existing Compose JSON logs timing race; its precise serialized-cap unit passed 1/1, and the bounded real-host JSON exec is covered by the dual-service E2E.
// Contract: The guide describes unchanged no-flag session status and the bounded `vat k8s session status --verify-api <id>` proof: only an active unexpired lease without a port-forward or exec marker may enter the private operation lock; it rechecks expiry after lock and immediately before the bounded private-credential API probe, verifies exact backing identity/endpoint, reports api_checked=true/api_state=reachable on success, returns non-probing api_checked=false/api_state=not_checked for expired/recovery state, and fails closed without lease/credential mutation for busy, unavailable, or identity-mismatched state. It remains one-boot/nonpersistent with no GUI or Docker Engine/API; focused fake coverage passed 4/4, a precise unit passed 1/1, and the independent-kubectl leased E2E passed 1/1 (36 filtered) in 29.97s with status --verify-api after text and strict JSON exec. That is bounded active-lease evidence, not a general API-status guarantee.
// Contract: The guide describes bounded text `vat k8s session exec [--timeout SECONDS] <id> -- COMMAND` and JSON `vat k8s session exec --format json [--timeout SECONDS] <id> -- COMMAND`: omission uses remaining TTL; explicit 1..=14400 seconds cannot exceed it. Both forms validate the active lease, exact backing/API identity, private credentials, and owned host API under the private lock, recheck expiry before spawn, own/reap the process group on normal exit, deadline, or interruption, and retain the lock through cleanup. A starting/live crash marker blocks later exec/delete/cleanup fail-closed rather than claiming termination. JSON returns one `vat.k8s.session.exec.v1`/`vat_json` document with child_exit_code, separate stdout/stderr with 64 KiB serialized-value caps and truncated/utf8-lossy indicators, api_verified=true, runtime_invoked=true, session_record_mutated=false, no raw replay, and no private paths. The leased real-host E2E passed 1/1 (36 filtered) in 29.97s, including JSON exec with `--timeout 30`, status verification, and exact delete.
// Contract: The guide describes unchanged text Service-forward and only `vat k8s session port-forward run --format json <id> service/<name> <port> -- COMMAND` for JSON: its loopback Service tunnel gives a credential-free child endpoint metadata, keeps the lock through shared-PGID cleanup, silently rechecks TTL after API proof and before exact kubectl/child spawn, then emits one post-cleanup `vat.k8s.session.port-forward.v1` document with child exit, separate 64 KiB serialized streams, no raw replay, masked VAT-owned failures, opaque-child preservation, and status-verify next. Partial reader setup cleans direct/outer children before reader joining. The independent-kubectl real-host E2E passed 1/1 (36 filtered) in 49.57s, covering one loopback Service text and strict JSON tunnel with confirmed cleanup and closed local ports; it is not a general tunnel guarantee.
// Contract: The guide describes strict direct inventory only as `docker ps --format json` / equals with optional exactly-once `--all` or `-a`, shared only by `docker container ls` and `docker container list`; `docker container ps` JSON remains rejected. It invokes `container list --format json [--all]`, validates one opaque Apple-native JSON value, then byte-for-byte replays stdout without a VAT wrapper or Docker Engine ps schema. Templates/table output, filter, quiet plus JSON, duplicate/unknown flags, and positionals fail before Apple Container. It is read-only inventory, not ownership/health/readiness/liveness proof; one five-second bounded isolated cleanup path covers root exit and both pipe EOFs, and malformed, oversized, or escaped-pipe output fails closed without stdout replay. Cargo check passed; shared docker_shim lib passed 54/54; focused ps fake integration passed 4/4; the full serial fake-shim aggregate is intentionally not recorded because an independent serial run exposed a nondeterministic pre-existing Compose JSON logs timing race; real-host observation passed 1/1 (50 filtered) on Apple Container 1.1.0; the temporary owner-labeled container uses a high-entropy name plus exact owner-label rechecks as conservative best-effort; the emergency guard retains on uncertainty; Apple Container has no atomic conditional delete, so there is no race-free/no-impossible-misdelete claim; ps is a global read-only inventory smoke observation, not a targeted ownership result, and proves one valid native JSON document only; fake/unit tests prove byte-preservation and fail-closed details
// Contract: The guide describes strict image inventory only as `docker images --format json` / equals, shared only by `docker image ls` and `docker image list`. It invokes `container image list --format json`, bounded-captures and validates one opaque Apple-native JSON value, then byte-for-byte replays stdout without a VAT wrapper or Docker Engine image schema. Template/table/YAML/TOML output, filters, quiet, verbose, all, digests, no-trunc, positionals, duplicates, unknown flags, and `--` fail before Apple Container; text/quiet image-list behavior remains inherited. It makes no ownership/provenance/security/executability/registry/build-readiness/health/readiness/liveness claim. A five-second bounded isolated cleanup path covers root exit and both pipe EOFs, and malformed, oversized, or escaped-pipe output fails closed without stdout replay. Cargo check passed; shared docker_shim lib passed 54/54; focused docker_images_json integration passed 4/4; the full serial fake-shim aggregate is intentionally not recorded because an independent serial run exposed a nondeterministic pre-existing Compose JSON logs timing race; real-host observation passed 1/1 (50 filtered) on Apple Container 1.1.0; the temporary owner-labeled container uses a high-entropy name plus exact owner-label rechecks as conservative best-effort; the emergency guard retains on uncertainty; Apple Container has no atomic conditional delete, so there is no race-free/no-impossible-misdelete claim; images is a global read-only inventory smoke observation, not a targeted ownership result, and proves one valid native JSON document only; fake/unit tests prove byte-preservation and fail-closed details
// Contract: The guide describes strict direct image inspect only as `docker image inspect --format json IMAGE` / equals: one JSON selector precedes exactly one opaque safe image reference, then VAT strips that selector and invokes only `container image inspect IMAGE`. Templates, `--`, extra references, and every other option reject before Apple Container; bounded capture validates one opaque Apple-native JSON document before byte-for-byte replay, preserves valid JSON plus a nonzero child exit, and suppresses malformed, oversized, or escaped-pipe output. It provides no Docker image-inspect schema/template/Engine API, provenance, security, registry, build-completion, readiness, or secret-redaction claim. Cargo check passed; docker_shim lib passed 58/58; focused docker_image_inspect_json passed 4/4 with 1 ignored; the opt-in host E2E passed 1/1 (61 filtered) in 1.21s and proves only one direct native image document.
// Contract: The guide describes strict `docker stats --no-stream --format json CONTAINER [CONTAINER...]` / equals form as read-only native Apple JSON, not a VAT/Docker Engine wrapper/schema or ownership/health/liveness proof. It uses a five-second bounded isolated cleanup path, replays only complete 256 KiB-capped validated capture, and fails closed without stdout replay for malformed, oversized, or escaped-pipe output. Shared strict-native-observation library coverage passed 54/54; the full serial fake-shim aggregate is intentionally not recorded because an independent serial run exposed a nondeterministic pre-existing Compose JSON logs timing race; real-host observation passed 1/1 (50 filtered) on Apple Container 1.1.0; stats targets the temporary owner-labeled container, whose high-entropy name plus exact owner-label rechecks are conservative best-effort; the emergency guard retains on uncertainty; Apple Container has no atomic conditional delete, so there is no race-free/no-impossible-misdelete claim; it proves one valid native JSON document only; fake/unit tests prove byte-preservation and fail-closed details
// Contract: The guide preserves permanent headless, non-Docker, non-daemon, full capabilities versus selected-plan doctor semantics: a full Docker probe maps `services.docker_services` to available or unavailable; `vat capabilities` exposes only a bounded read-only shared-builder advisory (shared_unknown ownership, automatic_cleanup=false, separate configuration/observed stats/global disk, nonfatal timeout/unknown/probe errors, no lifecycle mutation). An explicit Apple-Container-only plan uses one read-only container status probe and executes no Docker command; it maps `services.docker_services` to not_probed, retains `docker.daemon_probe.state=skipped` as provenance, and makes daemon=false non-unavailable evidence. Unsupported no-OCI-route presets and named volumes fail closed; builder advisory never decides doctor runtime success; Docker/Auto/cluster retains probe. K3s remains one-boot/local-lease only and requires an independently installed kubectl on PATH before K3s use. Independent-kubectl one-shot, leased, local-image, and Service-forward E2Es passed 1/1 (36 filtered) in 28.38s, 29.97s, 49.73s, and 49.57s. The local-image result is one already-local Apple alpine:3.20 pod with imagePullPolicy=Never, a marker log, and exact session cleanup; it does not establish registry-pull generality, persistence, GUI, or Docker Engine/API. The leased result covers strict JSON exec with `--timeout 30` and bounded `status --verify-api`; the Service-forward result covers one Service-only loopback strict JSON tunnel with a credential-free child, confirmed cleanup, and closed local ports. It adds no durable status backend: `status --verify-api` remains a private-lock, identity/endpoint, expiry-rechecked bounded active-lease proof, while `session exec --format json` is a credentialed agent-result form with no raw replay or session mutation. Those results do not establish persistence, a general cluster/tunnel, OS isolation, or crash-safe termination. It also preserves the opt-in shim, three-profile Compose, detached-only bounded wait (one wait, positive 300-default/1200-max timeout after import/build, durable VAT-only proof, target pinning, lock-free polls, safe timeout/next behavior, and verified-ready source-build cleanup), host-facing no-DNS/loopback-only JSON, exact ps topology with endpoint-proof gating and no --format/app-healthcheck claim, provenance isolation, text logs/exec with new-line additive handoffs plus strict VAT-native JSON exec, and no-Docker-Engine boundaries. The recorded opt-in gated dual-service E2E passed 1/1 (50 filtered) in 4.54s only for host-facing-independent-v1 up-wait/endpoints, one-document JSON ps/logs/exec, text logs, no-final-newline text-exec handoff, and down cleanup, never as service DNS, general Compose, Docker Engine API, or Kubernetes evidence.
// Contract: The guide describes strict direct container inspect only as `docker inspect --format json CONTAINER` / `--format=json`, shared only by `docker container inspect`: one safe id follows one VAT-only selector before runtime, unformatted inspect remains inherited, and canonical `container inspect CONTAINER` returns one complete validated Apple-native JSON document byte-for-byte without a VAT or Docker Engine inspect schema. It rejects `--type`, `--size`, templates/table/YAML/TOML, filters, a second id, `--`, and unknown flags; five-second bounded isolated cleanup covers root exit and both pipe EOFs, each stream is 256 KiB, valid JSON with a nonzero child exit preserves status, and malformed/oversized/flood output suppresses raw stdout. It supplies no ownership/provenance/security/image/registry/build-status/health/readiness/liveness/port-reachability proof or secret-redaction guarantee. Cargo check passed; shared docker_shim lib passed 54/54; focused docker_inspect integration passed 5/5; the full serial fake-shim aggregate is intentionally not recorded because an independent serial run exposed a nondeterministic pre-existing Compose JSON logs timing race; real-host observation passed 1/1 (50 filtered) on Apple Container 1.1.0; inspect targets the temporary owner-labeled container, whose high-entropy name plus exact owner-label rechecks are conservative best-effort; the emergency guard retains on uncertainty; Apple Container has no atomic conditional delete, so there is no race-free/no-impossible-misdelete claim; it proves one valid native JSON document only; fake/unit tests prove byte-preservation and fail-closed details
// Contract: The guide describes direct logs JSON as a separate finite VAT wrapper, not a sixth Apple-native form: only direct `docker logs --format json --tail LINES CONTAINER` / equals forms and the same form through `docker container logs` pass; one format and one tail may mix spelling but must precede one safe final id, and LINES is 1..=1000. Unformatted logs stay inherited, the selector is never forwarded, and canonical backend argv is `container logs -n LINES CONTAINER`. Apple text stdout becomes exactly one `vat.docker.logs.v1` / `vat_json` wrapper with untrusted stdio, bounded diagnostic stderr, truncation/lossy flags, backend/container/requested_tail/runtime/child outcome, and safe inspect next—not Docker schema/multiplex/demux. Ordinary child nonzero retains wrapper+exit; follow/boot/timestamps/since/until/templates and all other modifiers reject before runtime, while timeout/setup/escaped-pipe failure emits no partial wrapper after five-second plus one-second bounded dual-stream suffix/serialized caps. Cargo check passed; docker_shim lib passed 54/54; focused docker_logs_json integration passed 6/6; the full serial aggregate is intentionally not recorded because of the nondeterministic pre-existing Compose JSON logs timing race. `VAT_DOCKER_SHIM_E2E_REQUIRED=1 cargo test -p vat --test vat_docker_shim apple_container_docker_run_published_port_contract -- --ignored --nocapture` passed 1/1 (50 filtered) on Apple Container 1.1.0: logs targets a temporary owner-labeled container; its high-entropy name plus exact owner-label rechecks are conservative best-effort; the emergency guard retains on uncertainty; Apple Container has no atomic conditional delete, so there is no race-free/no-impossible-misdelete claim; the shared/cacheable nginx image is not cleaned up. The host smoke proves one wrapper only; fake/unit tests prove byte-preservation and fail-closed details.
// Contract: The guide documents direct exec JSON only as `docker exec --format json --timeout SECONDS CONTAINER -- COMMAND [ARG...]` / equals forms and `docker container exec`: exact one format plus one 1..=1200 timeout precede one safe id and a mandatory Docker-facing delimiter/raw command; raw exec remains inherited. VAT strips its selectors and delimiter before `container exec CONTAINER COMMAND [ARG...]`, emits one `vat.docker.exec.v1` / `vat_json` wrapper with separate serialized-64-KiB-capped untrusted streams and `timeout_scope=host-container-client-observation`, preserves ordinary child failure wrapper+exit, and emits no partial wrapper on timeout/setup/capture failure. The timeout does not claim guest termination. Deterministic docker_shim lib validation passed 54/54 and focused docker_exec_json passed 4/4; the direct real-host E2E passed 1/1 (50 filtered) on Apple Container 1.1.0 with an exec wrapper containing both stdout/stderr markers. The temporary owner-labeled container uses a high-entropy name plus exact owner-label rechecks as conservative best-effort; the emergency guard retains on uncertainty; Apple Container has no atomic conditional delete, so there is no race-free/no-impossible-misdelete claim. It is not Docker Engine parity, generic runtime, Compose, or Kubernetes evidence.
// Contract: The emitted guide documents the strict direct run JSON one-shot: only direct docker run with flexible-order format/timeout selectors before IMAGE, 1..=1200 timeout, raw command argv directly after IMAGE, a Docker `--` rejected before IMAGE or immediately after it but opaque child argv after the first non-`--` command token, caller lifecycle/network/mount/env options rejected before runtime, one owner-cleaned vat.docker.run.v1 result after exact absence, and no partial wrapper on timeout/setup/cleanup uncertainty. It preserves the narrow evidence: deterministic docker_run_json 5 plus 1 ignored in 1.80s and local alpine E2E 1/1 (56 filtered) in 2.30s, without guest-wide termination, crash-recovery, Docker Engine, or redaction claims.
// Contract: The emitted guide documents the strict direct build JSON receipt: only direct docker build with exact json/1..=1200-timeout/tag selectors, documented optional file/build-arg/target/platform/label fields before one canonical existing local-directory context, and no `--`, second context, or unsupported/misordered form. It strips only JSON/deadline selectors for public container build, returns one bounded vat.docker.build.v1 receipt with retained_no_auto_cleanup, safe success image-inspect next, and normal nonzero build_failed/docker-help without stale inspect; timeout/setup/capture emits no receipt. The deadline is host observation only, never cancellation/rollback/removal, and no Engine/provenance/ownership/readiness/security/redaction claim follows. It records 62/62 library, focused 4 plus 1 ignored (63 filtered), owner guard 1/1 (67 filtered), and opt-in host receipt E2E 1/1 (67 filtered) in 2.53s. The host test's high-entropy tag/exact label plus absence checks are test-only best effort; a race leaks rather than turning product builds into auto-cleanup.
// Contract: The emitted guide documents the strict direct pull JSON receipt: only direct docker pull with one json and one 1..=1200 timeout selector before one safe opaque image reference (nonempty, no leading dash, whitespace/control, URL-style `://`, or leading Git-style `git@` remote; ordinary OCI `@digest` remains opaque); `--`, second reference, missing/duplicate/misordered selectors, and unsupported flags reject before the client, while raw unselected direct pull and docker image pull remain inherited. It strips only JSON/deadline selectors for public container image pull and returns one bounded vat.docker.pull.v1 receipt with not_owned_no_auto_cleanup and absent registry-management/auth lifecycle. Success has strict image-inspect next without image-state/download-completion proof; ordinary nonzero is pull_failed/docker-help without stale inspect; timeout/setup/capture/pipe failure has no receipt. Host deadline is client/pipes observation only, not transfer cancellation/download completion/rollback/local-or-backend image state. It records 65/65 library, focused 5 plus 1 ignored (68 filtered), and opt-in host E2E 1/1 (73 filtered) in 27.14s; the real shared alpine cache probe deletes nothing and asserts no image ownership.
#[test]
#[ignore = "AW EC gate: run via `aw health --verify-ec` or `cargo test -- --ignored`"]
fn vat_llm_agent_usage_guide() {
    let command = "cargo test -p vat --test vat_toml_runner -- --nocapture";
    let id = "vat-llm-agent-usage-guide";
    let mut root = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    while !root.join(".aw").is_dir() {
        assert!(
            root.pop(),
            "AW EC {id}: no .aw/ project root above {}",
            env!("CARGO_MANIFEST_DIR")
        );
    }
    let output = std::process::Command::new("sh")
        .arg("-c")
        .arg(command)
        .current_dir(&root)
        .output()
        .unwrap_or_else(|e| panic!("AW EC {id}: failed to spawn `{command}`: {e}"));
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);
    if output.status.success()
        && aw_ec_cargo_test_executed_count(command, &stdout, &stderr) == Some(0)
    {
        panic!("AW EC {id} FAILED: cargo test command passed but executed 0 tests: {command}\nstdout:\n{stdout}\nstderr:\n{stderr}");
    }
    assert!(
        output.status.success(),
        "AW EC {id} FAILED (exit {:?}): {command}\nstdout:\n{stdout}\nstderr:\n{stderr}",
        output.status.code()
    );
}

fn aw_ec_cargo_test_executed_count(command: &str, stdout: &str, stderr: &str) -> Option<usize> {
    if !command.contains("cargo test") {
        return None;
    }
    let mut total = 0usize;
    let mut saw_count = false;
    for line in stdout.lines().chain(stderr.lines()) {
        let Some(count) = aw_ec_parse_cargo_running_test_count(line) else {
            continue;
        };
        total = total.saturating_add(count);
        saw_count = true;
    }
    saw_count.then_some(total)
}

fn aw_ec_parse_cargo_running_test_count(line: &str) -> Option<usize> {
    let rest = line.trim().strip_prefix("running ")?;
    let number = rest
        .strip_suffix(" tests")
        .or_else(|| rest.strip_suffix(" test"))?;
    number.trim().parse().ok()
}
// CODEGEN-END
